apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::431990627878:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JBDY4UVRPOXN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::431990627878:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-11T11:36:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1622"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf7447a6-8676-42cf-a54c-2d14c9a0a44f
